#include <stdio.h>
#include <errno.h>      //errno variable is defined in this library
#include<string.h>      //includes strerror function

extern int errno;       // I don't need to declare errno myself if i include the errno.h header file in your program, as this file already declares errno as an external variable. but here i declared again:)

int main() {
    FILE *ptr;
    printf("errno before: %d\n", errno);

    ptr = fopen("hi.txt", "r");

    if(ptr == NULL){
        printf("errno after: %d\n", errno);   //output 2 reprasent error, "No such file or directory"
        printf("error msg: %s\n", strerror(errno));     //try to use fprintf here too
        fprintf(stderr, "errno after: %d\n", errno);    //use fprintf insteed of printf in this issue, details on the video

        perror("error message");    //it wil take this string and put a colon and space right after it and put the error msg using "errno" variable
    }
    else
        fclose(ptr);
    return 0;
}

/*
The errno.h library in C provides a way for C programs to handle error conditions that occur during program execution. This library defines a set of integer error codes that can be used to identify specific errors that occur while running a program.
The errno variable is defined in this library and is used to store the error code generated by the function that detects the error. The error codes are defined as constants and can be accessed through the errno.h library.When an error occurs, the function that detected the error sets the errno variable to the appropriate error code, and the program can use this code to take appropriate action


By declaring extern int errno; in your program, you are telling the compiler that you want to use the errno variable in your program, and that the actual definition of the errno variable will be provided by the C library at link time. This is known as an external declaration. The statement extern int errno; is a declaration that informs the C compiler that the variable errno is defined in another file or library, and that the current program needs to use it.The errno variable is used to store error codes that are set by various functions in the C library when they encounter an error condition. By default, errno is declared in the header file errno.h, but it is defined in the C library. SO I DON'T NEED TO WRITE "extern int errno" IF I INCLUDE ERRNO.H HEADER FILE.
*/