#include <stdio.h>

int main() {
    char fileName[L_tmpnam];
    tmpnam(fileName);
    printf("%s\n", fileName);

    //In this example, L_tmpnam is a macro that represents the minimum length of a buffer that can hold the filename generated by tmpnam. The function generates a unique filename and stores it in the filename array, which is then printed to the console. Note that the filename generated by tmpnam may not actually correspond to a file on disk, and it should only be used as a temporary filename.

    char *filename2 = tmpnam(NULL);     //if we pass null through tmpnam, it'll return a pointer to string
    printf("%s\n", filename2);
    
    //It's worth noting that the buffer allocated by tmpnam is only guaranteed to be valid until the next call to tmpnam or tmpfile. Therefore, if the generated filename needs to be used for an extended period of time, it should be copied to a separate buffer to ensure that it is not overwritten by subsequent calls to tmpnam or tmpfile.

    FILE *file = fopen(fileName, "w");
    if(file == NULL){
        printf("Error opening tempmorary file\n");
        return 1;
    } else
        fprintf(file, "some contents\n");

    fclose(file);

    remove(fileName);       //remove the temp file after done work with it
    
}