# Generated by Django 5.2.7 on 2025-10-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User_ Info',
        ),
    ]
