# Generated by Django 5.2.7 on 2025-10-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMLearning', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
