# Generated by Django 5.2.7 on 2025-10-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMLearning', '0003_rename_user_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Customer',
        ),
    ]
