# Generated by Django 5.2.7 on 2025-11-03 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(unique=True)),
                ('department', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('student_img', models.ImageField(blank=True, help_text='Upload a image in jpg, png, jpeg format', null=True, upload_to='pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('cv', models.FileField(blank=True, help_text='Upload a pdf file', null=True, upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
