# Generated by Django 5.2.7 on 2025-11-03 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_pdf',
            field=models.FileField(blank=True, null=True, upload_to='problem_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
