# Generated by Django 5.2.7 on 2025-11-03 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_problem_problem_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='online_judge',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('CodeForces', 'CodeForces'), ('CodeChef', 'CodeChef'), ('AtCoder', 'AtCoder'), ('GeeksforGeeks', 'GeeksforGeeks'), ('Other', 'Other')], default='LeetCode', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_pdf',
            field=models.FileField(blank=True, help_text='Upload a PDF file for the problem', null=True, upload_to='problem_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
