# Generated by Django 5.2.7 on 2025-11-04 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_problem_online_judge_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_pdf',
            field=models.FileField(blank=True, help_text='Upload a PDF file for the problem', null=True, upload_to='Problem PDF/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
