# Generated by Django 5.2.7 on 2025-11-04 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_problem_problem_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='online_judge',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('CodeForces', 'CodeForces'), ('CodeChef', 'CodeChef'), ('AtCoder', 'AtCoder'), ('GeeksforGeeks', 'GeeksforGeeks'), ('Other', 'Other')], default='CodeForces', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_pdf',
            field=models.FileField(blank=True, help_text='Upload a PDF file for the problem', null=True, upload_to='Problem_PDF/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
