# Generated by Django 5.2.7 on 2025-11-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
